name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.143.1'  # Updated to the desired version

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read  # Add this line to grant artifact access

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Manually set up Hugo
      - name: Setup Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${{ env.WC_HUGO_VERSION }}/hugo_extended_${{ env.WC_HUGO_VERSION }}_Linux-64bit.tar.gz
          tar -xvzf hugo_extended_${{ env.WC_HUGO_VERSION }}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/

      # Clear Hugo cache
      - name: Clear Hugo cache
        run: |
          rm -rf /tmp/hugo_cache_runner/

      # Manually configure Pages
      - name: Setup Pages
        run: |
          echo "base_url=https://${{ github.repository_owner }}.github.io/${{ github.repository }}" >> $GITHUB_ENV

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
          hugo --minify --baseURL "${{ env.base_url }}"

      # Debug: List files in the public directory
      - name: List files after Hugo build
        run: ls -R ./public

      # Debug: Confirm public directory exists and contains files
      - name: Debug public directory
        run: |
          echo "Contents of public directory:"
          ls -R ./public

      - name: Generate Pagefind search index
        run: npx pagefind --site "public"

      # Upload the public directory as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          name: github-pages  # Add this line
          
      - name: Confirm Hugo Output Directory
        run: |
          if [ -d "./public" ]; then
          echo "Public directory exists."
          else
          echo "Public directory does NOT exist!"
          exit 1
          fi
      - name: Clear GitHub Actions Cache
        run: |
          rm -rf ~/.cache
    

  deploy:
    if: github.repository_owner != 'HugoBlox'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages
      - name: List files
        run: ls -R
